### ISSUE TITLE
Lightcone and Character Ascension Bug

### ISSUE THREAD

**Issue by lineyleen** [EggLink/DanhengServer-Public#3]
The Game gets frozen while ascending characters or lightcones.

And sometimes pulling a 5* freezes the screen. Tapping on it, the screen does not go away.

**Comment by sunjunps** [comment]
me too.
it's a known bug, maybe it will be fixed in 2.3

**Comment by EggLink** [comment]
wait it to be fixed :)

**Comment by EggLink** [comment]
solved in next ver
